package org.errorexception.university;

public enum Subject {
    ARTIFICIAL_INTELLIGENCE,
    PROGRAMMING_LANGUAGES_AND_LOGIC,
    SCIENTIFIC_COMPUTING_APPLICATIONS,
    THEORY_OF_COMPUTATION,
    DATA_STRUCTURES_AND_ALGORITHMS,
    COMPUTER_ARCHITECTURE_AND_ORGANISATION,
    COMPUTER_NETWORKS,
    COMPUTER_SECURITY_AND_CRYPTOGRAPHY,
    DATABASES_AND_DATA_MINING,
    COMPUTER_GRAPHICS,
    SOFTWARE_ENGINEERING
}
